spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro-jwt?characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhapeng213.
  redis:
    host: localhost
    database: 0
    port: 6379
    ## 连接超时时间（毫秒）
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        # 连接池阻塞等待时间（负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中最小空闲连接
        min-idle: 0

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/xml/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.jiezhan.auth.model.entity
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    # 字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 1
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    #    refresh-mapper: true
    # 数据库大写下划线转换
  #    capital-mode: true

  configuration:
    # 配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 配置JdbcTypeForNull, oracle数据库必须配置
    # jdbc-type-for-null: 'null'

expoProtoco: http
expoIp: localhost
expoPort: 20090